# Site settings
title: The Data-Sitters Club
description: > # this means to ignore newlines until "baseurl:"
  Need a Data-Sitter? <br> Save time!<br> Call The Data-Sitters Club.
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "datasittersclub.github.io" # the base hostname & protocol for your site
twitter_username: datasittersclub
github_username: datasittersclub

# Build settings
markdown: kramdown
permalink: pretty